### PR TITLE
Add static helper method

### PR DESCRIPTION
**Pull request by F43nd1r**
The code in the readme is really just boilerplate code, which could be easily extracted in a static helper, as I just did here. I also adjusted the sample to show how it's used.

### CODE REVIEW

**Comment by spacecowboy** [comment]
I like it!

Couple of things:

- will likely conflict with
https://github.com/spacecowboy/NoNonsense-FilePicker/pull/118 which I'm
planning on merging any day now.
- the method should be in AbstractFilePickerActivity because it's general
functionality
- some tests would be nice (but I can add those if that's problematic)

**Comment by F43nd1r** [comment]
I haven't looked at the beta yet. I'll definetly wait for the merge and then check back how this can fit with it.
I wasn't sure about the class, as a static method like this could be anywhere, so I just used the only class I already had in my imports.

One question: Are there any resources how to use this library to access files which can only be reached through the SAF?

**Comment by spacecowboy** [comment]
The conflict is my problem though so don't worry about that point

**Comment by spacecowboy** [comment]
@F43nd1r you mean like physical SD cards? That is still an open question. There doesn't seem to be a way to access them outside of SAF.

**Comment by spacecowboy** [comment]
Sorry for the delay @F43nd1r . I just kind of forgot about this PR.

Rebased and moved this functionality in https://github.com/spacecowboy/NoNonsense-FilePicker/pull/138

**Pull request closed without merging**
